In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

file_name = "employee_productivity_dataset.csv"

try:
    df = pd.read_csv(file_name)
except FileNotFoundError:
    print(f"{file_name} file not found.")

Q1. Handle Missing Values (Basic Cleaning)

Fill missing values using the following:

- Age → Median
- Salary → Mean
- Hours_Worked_Per_Week → Median
- Performance_Score → Mean

Display the dataset after handling missing values.

In [4]:
q1_df = df.copy()

q1_df["Age"] = q1_df["Age"].fillna(q1_df["Age"].median())
q1_df["Salary"] = q1_df["Salary"].fillna(q1_df["Salary"].mean())
q1_df["Hours_Worked_Per_Week"] = q1_df["Hours_Worked_Per_Week"].fillna(q1_df["Hours_Worked_Per_Week"].median())
q1_df["Performance_Score"] = q1_df["Performance_Score"].fillna(q1_df["Performance_Score"].mean())

q1_df

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5000,50000.000000,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0000,45000.000000,Mumbai
2,E003,John Mathew,Finance,29.0,Male,Onsite,10-03-2022,45.0,6,4.3125,60000.000000,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,41.0,5,4.2000,52000.000000,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8000,50666.666667,Pune
...,...,...,...,...,...,...,...,...,...,...,...,...
245,E006,Neha Singh,HR,27.0,Female,Remote,01-06-2023,36.0,3,3.9000,42000.000000,Mumbai
246,E007,Rahul Das,Finance,40.0,Male,Onsite,07-07-2019,48.0,8,4.7000,65000.000000,Delhi
247,E008,Pooja Mehta,Marketing,29.0,Female,Hybrid,12-08-2022,42.0,6,4.3000,48000.000000,Bangalore
248,E009,Sameer Khan,IT,31.0,Male,Remote,30-09-2021,41.0,5,4.1000,51000.000000,Pune
249,E010,Kiran Nair,HR,26.0,Female,Onsite,05-10-2023,37.0,4,4.3125,43000.000000,Mumbai

Q2. Label Encoding

Convert these columns into numeric values using Label Encoding:

- Gender
- Department

Show the updated columns.

In [5]:
q2_df = q1_df.copy()

gender_encoder = LabelEncoder()
department_encoder = LabelEncoder()

q2_df["Gender"] = gender_encoder.fit_transform(q2_df["Gender"])
q2_df["Department"] = department_encoder.fit_transform(q2_df["Department"])

q2_df[["Gender", "Department"]]

     Gender  Department
0         1           2
1         0           1
2         1           0
3         0           2
4         1           3
..      ...         ...
245       0           1
246       1           0
247       0           3
248       1           2
249       0           1

[250 rows x 2 columns]

Q3. One-Hot Encoding

Apply One-Hot Encoding on:

- Work_Mode
- Location

Display the dataset and check how many new columns are created.

In [6]:
q3_df = pd.get_dummies(q2_df, columns=["Work_Mode", "Location"])

new_columns = [col for col in q3_df.columns if col.startswith("Work_Mode_") or col.startswith("Location_")]

print("New columns created:", len(new_columns))
print(new_columns)

q3_df

New columns created: 7
['Work_Mode_Hybrid', 'Work_Mode_Onsite', 'Work_Mode_Remote', 'Location_Bangalore', 'Location_Delhi', 'Location_Mumbai', 'Location_Pune']

,Employee_ID,Name,Department,Age,Gender,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Work_Mode_Hybrid,Work_Mode_Onsite,Work_Mode_Remote,Location_Bangalore,Location_Delhi,Location_Mumbai,Location_Pune
0,E001,Amit Sharma,2,25.0,1,15-01-2021,40.0,5,4.5000,50000.000000,False,False,True,False,False,False,True
1,E002,Riya Patel,1,30.0,0,15-02-2020,38.0,4,4.0000,45000.000000,True,False,False,False,False,True,False
2,E003,John Mathew,0,29.0,1,10-03-2022,45.0,6,4.3125,60000.000000,False,True,False,True,False,False,False
3,E004,Sneha Joshi,2,28.0,0,22-04-2021,41.0,5,4.2000,52000.000000,False,False,True,False,True,False,False
4,E005,Arjun Verma,3,35.0,1,18-05-2020,50.0,7,4.8000,50666.666667,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,E006,Neha Singh,1,27.0,0,01-06-2023,36.0,3,3.9000,42000.000000,False,False,True,False,False,True,False
246,E007,Rahul Das,0,40.0,1,07-07-2019,48.0,8,4.7000,65000.000000,False,True,False,False,True,False,False
247,E008,Pooja Mehta,3,29.0,0,12-08-2022,42.0,6,4.3000,48000.000000,True,False,False,True,False,False,False
248,E009,Sameer Khan,2,31.0,1,30-09-2021,41.0,5,4.1000,51000.000000,False,False,True,False,False,False,True
249,E010,Kiran Nair,1,26.0,0,05-10-2023,37.0,4,4.3125,43000.000000,False,True,False,False,False,True,False

Q4. Normalization (Min-Max Scaling)

Normalize the following columns:

- Salary
- Hours_Worked_Per_Week

Use MinMaxScaler and display results.

In [7]:
q4_df = q3_df.copy()

minmax_scaler = MinMaxScaler()
q4_df[["Salary", "Hours_Worked_Per_Week"]] = minmax_scaler.fit_transform(
    q4_df[["Salary", "Hours_Worked_Per_Week"]]
)

q4_df[["Salary", "Hours_Worked_Per_Week"]]

       Salary  Hours_Worked_Per_Week
0    0.347826               0.285714
1    0.130435               0.142857
2    0.782609               0.642857
3    0.434783               0.357143
4    0.376812               1.000000
..        ...                    ...
245  0.000000               0.000000
246  1.000000               0.857143
247  0.260870               0.428571
248  0.391304               0.357143
249  0.043478               0.071429

[250 rows x 2 columns]

Q5. Standardization (Scaling)

Apply StandardScaler on:

- Age
- Projects_Completed

Display the transformed values.

In [8]:
q5_df = q4_df.copy()

standard_scaler = StandardScaler()
q5_df[["Age", "Projects_Completed"]] = standard_scaler.fit_transform(
    q5_df[["Age", "Projects_Completed"]]
)

q5_df[["Age", "Projects_Completed"]]

          Age  Projects_Completed
0   -1.172018           -0.211604
1    0.000000           -0.916949
2   -0.234404            0.493742
3   -0.468807           -0.211604
4    1.172018            1.199088
..        ...                 ...
245 -0.703211           -1.622295
246  2.344036            1.904433
247 -0.234404            0.493742
248  0.234404           -0.211604
249 -0.937614           -0.916949

[250 rows x 2 columns]

Q6. Compare Scaling Methods

Apply both:

- MinMaxScaler
- StandardScaler

On the Salary column.

Show both results side by side.

In [9]:
salary_compare = q1_df[["Salary"]].copy()

salary_minmax = MinMaxScaler()
salary_standard = StandardScaler()

compare_df = pd.DataFrame({
    "Salary_MinMaxScaler": salary_minmax.fit_transform(salary_compare).flatten(),
    "Salary_StandardScaler": salary_standard.fit_transform(salary_compare).flatten()
})

compare_df

     Salary_MinMaxScaler  Salary_StandardScaler
0               0.347826              -0.097451
1               0.130435              -0.828333
2               0.782609               1.364312
3               0.434783               0.194902
4               0.376812               0.000000
..                   ...                    ...
245             0.000000              -1.266862
246             1.000000               2.095194
247             0.260870              -0.389804
248             0.391304               0.048725
249             0.043478              -1.120685

[250 rows x 2 columns]

Q7. Build Preprocessing Pipeline

Create a pipeline that:

- Applies encoding to categorical columns
- Applies scaling to numerical columns

Use:

- ColumnTransformer
- Pipeline

In [10]:
categorical_columns = ["Gender", "Department", "Work_Mode", "Location"]
numerical_columns = ["Age", "Salary", "Hours_Worked_Per_Week", "Projects_Completed", "Performance_Score"]

categorical_pipeline = Pipeline(steps=[
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

numerical_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler())
])

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", categorical_pipeline, categorical_columns),
        ("num", numerical_pipeline, numerical_columns)
    ]
)

pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor)
])

pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Gender', 'Department',
                                                   'Work_Mode', 'Location']),
                                                 ('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Salary',
                                                   'Hours_Worked_Per_Week',
                                                   'Projects_Completed',
                                                   'Performance_Score'])]))])

Q8. Apply Pipeline

Apply the pipeline on the dataset.

Display:

- Transformed dataset
- Shape of final dataset

In [11]:
pipeline_data = q1_df[categorical_columns + numerical_columns].copy()

transformed_data = pipeline.fit_transform(pipeline_data)
feature_names = pipeline.named_steps["preprocessor"].get_feature_names_out()

transformed_df = pd.DataFrame(transformed_data, columns=feature_names)

print("Shape of final dataset:", transformed_df.shape)

transformed_df

Shape of final dataset: (250, 18)

,cat__Gender_Female,cat__Gender_Male,cat__Department_Finance,cat__Department_HR,cat__Department_IT,cat__Department_Marketing,cat__Work_Mode_Hybrid,cat__Work_Mode_Onsite,cat__Work_Mode_Remote,cat__Location_Bangalore,cat__Location_Delhi,cat__Location_Mumbai,cat__Location_Pune,num__Age,num__Salary,num__Hours_Worked_Per_Week,num__Projects_Completed,num__Performance_Score
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.172018,-0.097451,-0.411220,-0.211604,0.685224
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,-0.828333,-0.868132,-0.916949,-1.142041
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.234404,1.364312,0.731059,0.493742,0.000000
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,-0.468807,0.194902,-0.182765,-0.211604,-0.411135
4,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.172018,0.000000,1.873338,1.199088,1.781584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.703211,-1.266862,-1.325044,-1.622295,-1.507494
246,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2.344036,2.095194,1.416426,1.904433,1.416131
247,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.234404,-0.389804,0.045691,0.493742,-0.045682
248,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.234404,0.048725,-0.182765,-0.211604,-0.776588
249,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.937614,-1.120685,-1.096588,-0.916949,0.000000

Q9. Conceptual Question

Why is scaling important in Python?

In [12]:
answer_q9 = "Scaling is important because it brings values to a similar range, so large values do not dominate and many machine learning models work better."

print(answer_q9)

Scaling is important because it brings values to a similar range, so large values do not dominate and many machine learning models work better.

Q10. Conceptual Question

Why do we convert categorical data into numerical form?

In [13]:
answer_q10 = "We convert categorical data into numerical form because machine learning models work with numbers, not text values."

print(answer_q10)

We convert categorical data into numerical form because machine learning models work with numbers, not text values.