# NumPy & Pandas Assignment

## Link: Retail_Dataset

## Import Library and Load Dataset

**Answer:**

Below code loads `Retail_Dataset.csv`.  
If the file is not available, it creates a small sample dataset so the notebook can still run.

In [1]:
import pandas as pd
import numpy as np

try:
    df = pd.read_csv("Retail_Dataset.csv")
except FileNotFoundError:
    data = {
        "Date": ["2023-01-05", "2023-01-12", "2023-02-03", "2023-02-18", "2023-03-07",
                 "2023-03-15", "2023-04-01", "2023-04-20", "2023-05-09", "2023-05-25"],
        "Product Category": ["Electronics", "Clothing", "Grocery", "Electronics", np.nan,
                             "Clothing", "Furniture", "Grocery", "Electronics", "Furniture"],
        "Region": ["East", "West", "North", "South", "East",
                   np.nan, "West", "South", "North", "East"],
        "Quantity": [5, 10, np.nan, 7, 6, 8, 4, np.nan, 9, 3],
        "Price": [200.0, 50.0, 20.0, np.nan, 150.0, 80.0, 300.0, 25.0, np.nan, 400.0]
    }
    df = pd.DataFrame(data)

df

         Date Product Category Region  Quantity  Price
0  2023-01-05      Electronics   East       5.0  200.0
1  2023-01-12         Clothing   West      10.0   50.0
2  2023-02-03          Grocery  North       NaN   20.0
3  2023-02-18      Electronics  South       7.0    NaN
4  2023-03-07              NaN   East       6.0  150.0
5  2023-03-15         Clothing    NaN       8.0   80.0
6  2023-04-01        Furniture   West       4.0  300.0
7  2023-04-20          Grocery  South       NaN   25.0
8  2023-05-09      Electronics  North       9.0    NaN
9  2023-05-25        Furniture   East       3.0  400.0

## Question 1

**Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.**

**Answer:**

In [2]:
# First 5 rows
df.head()

         Date Product Category Region  Quantity  Price
0  2023-01-05      Electronics   East       5.0  200.0
1  2023-01-12         Clothing   West      10.0   50.0
2  2023-02-03          Grocery  North       NaN   20.0
3  2023-02-18      Electronics  South       7.0    NaN
4  2023-03-07              NaN   East       6.0  150.0

## Question 1 - Dataset Information

**Dataset information**

**Answer:**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              10 non-null     object
 1   Product Category  9 non-null      object
 2   Region            9 non-null      object
 3   Quantity          8 non-null      float64
 4   Price             8 non-null      float64
dtypes: float64(2), object(3)
memory usage: 532.0+ bytes

## Question 2

**Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset.**

**Answer:**

In [4]:
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values)

print("\nTotal missing values in the dataset:")
print(missing_values.sum())

Missing values in each column:
Date                0
Product Category    1
Region              1
Quantity            2
Price               2
dtype: int64

Total missing values in the dataset:
6

## Question 3

**Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.**

**Answer:**

In [5]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Price"] = df["Price"].fillna(df["Price"].mean())

df[["Quantity", "Price"]]

   Quantity    Price
0       5.0  200.000
1      10.0   50.000
2       6.5   20.000
3       7.0  153.125
4       6.0  150.000
5       8.0   80.000
6       4.0  300.000
7       6.5   25.000
8       9.0  153.125
9       3.0  400.000

## Question 4

**Q4. Remove all rows where the Product Category or Region column contains missing values.**

**Answer:**

In [6]:
df = df.dropna(subset=["Product Category", "Region"])
df

         Date Product Category Region  Quantity    Price
0  2023-01-05      Electronics   East       5.0  200.000
1  2023-01-12         Clothing   West      10.0   50.000
2  2023-02-03          Grocery  North       6.5   20.000
3  2023-02-18      Electronics  South       7.0  153.125
6  2023-04-01        Furniture   West       4.0  300.000
7  2023-04-20          Grocery  South       6.5   25.000
8  2023-05-09      Electronics  North       9.0  153.125
9  2023-05-25        Furniture   East       3.0  400.000

## Question 5

**Q5. Create a new column called Revenue using NumPy, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.**

**Answer:**

In [7]:
df["Revenue"] = np.multiply(df["Quantity"], df["Price"])
df

/tmp/ipykernel_210/1264273871.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Revenue"] = np.multiply(df["Quantity"], df["Price"])

         Date Product Category Region  Quantity    Price   Revenue
0  2023-01-05      Electronics   East       5.0  200.000  1000.000
1  2023-01-12         Clothing   West      10.0   50.000   500.000
2  2023-02-03          Grocery  North       6.5   20.000   130.000
3  2023-02-18      Electronics  South       7.0  153.125  1071.875
6  2023-04-01        Furniture   West       4.0  300.000  1200.000
7  2023-04-20          Grocery  South       6.5   25.000   162.500
8  2023-05-09      Electronics  North       9.0  153.125  1378.125
9  2023-05-25        Furniture   East       3.0  400.000  1200.000

## Question 6

**Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.**

**Answer:**

In [8]:
total_revenue = np.sum(df["Revenue"])
print("Total Revenue:", total_revenue)

Total Revenue: 6642.5

## Question 7

**Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.**

**Answer:**

In [9]:
category_revenue = df.groupby("Product Category")["Revenue"].sum()
category_revenue

Product Category
Clothing        500.0
Electronics    3450.0
Furniture      2400.0
Grocery         292.5
Name: Revenue, dtype: float64

## Question 8

**Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the highest revenue and the bottom 3 categories with the lowest revenue.**

**Answer:**

In [10]:
top_3_categories = category_revenue.sort_values(ascending=False).head(3)
bottom_3_categories = category_revenue.sort_values(ascending=True).head(3)

print("Top 3 Categories with Highest Revenue:")
print(top_3_categories)

print("\nBottom 3 Categories with Lowest Revenue:")
print(bottom_3_categories)

Top 3 Categories with Highest Revenue:
Product Category
Electronics    3450.0
Furniture      2400.0
Clothing        500.0
Name: Revenue, dtype: float64

Bottom 3 Categories with Lowest Revenue:
Product Category
Grocery       292.5
Clothing      500.0
Furniture    2400.0
Name: Revenue, dtype: float64

## Question 9

**Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the region with the highest revenue and the region with the lowest revenue.**

**Answer:**

In [11]:
region_revenue = df.groupby("Region")["Revenue"].sum()

print("Revenue by Region:")
print(region_revenue)

print("\nRegion with Highest Revenue:")
print(region_revenue.idxmax(), "-", region_revenue.max())

print("\nRegion with Lowest Revenue:")
print(region_revenue.idxmin(), "-", region_revenue.min())

Revenue by Region:
Region
East     2200.000
North    1508.125
South    1234.375
West     1700.000
Name: Revenue, dtype: float64

Region with Highest Revenue:
East - 2200.0

Region with Lowest Revenue:
South - 1234.375

## Question 10

**Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column using NumPy.**

**Answer:**

In [12]:
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.month

monthly_revenue = df.groupby("Month")["Revenue"].sum()

print("Monthly Revenue:")
print(monthly_revenue)

print("\nMean Revenue:", np.mean(df["Revenue"]))
print("Median Revenue:", np.median(df["Revenue"]))
print("Standard Deviation of Revenue:", np.std(df["Revenue"]))

Monthly Revenue:
Month
1    1500.000
2    1201.875
4    1362.500
5    2578.125
Name: Revenue, dtype: float64

Mean Revenue: 830.3125
Median Revenue: 1035.9375
Standard Deviation of Revenue: 461.8035296530333

/tmp/ipykernel_210/3712438447.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(df["Date"])
/tmp/ipykernel_210/3712438447.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month"] = df["Date"].dt.month